-[------->+<]>-.	PRINT 'S'
-[->+++++<]>++.		PRINT 'c'
----.			PRINT 'h'
++++.			PRINT 'o'
+++++++.		PRINT 'o'
----- -.-.-.		PRINT 'l'
>[-]+++++++++++.	PRINT ' '
+[-<+]-.		PRINT 'S'
[->+++++<]--.		PRINT 'c'
------.			PRINT 'h'
------.			PRINT 'o'
--.			PRINT 'o'
---.			PRINT 'l'
---------.		PRINT ' '
